name: ACS
version: '${project.version}'
main: foleon.acs.ACS
author: Foleon
api-version: 1.0.0-APLHA
description: ACS - Anti Cheat System
commands:
  acs:
    description: крутая команда
    permission: acs.use
